// Auto-generated by the Upload button (see lib/content-manifest.js).
// Add content via Upload in the app — do not hand-edit this file, it
// gets overwritten on the next upload to this subject.

import content_set_read_bonus_fog_quotations from "./set-read-bonus-fog-quotations.js";
import content_set_read_bonus_noticeboard from "./set-read-bonus-noticeboard.js";
import content_set_read_bonus_repair_caf_debate from "./set-read-bonus-repair-caf-debate.js";
import content_set_read_bonus_two_weather_records from "./set-read-bonus-two-weather-records.js";
import content_set_read_borrowing_voices from "./set-read-borrowing-voices.js";
import content_set_read_coastal_freight from "./set-read-coastal-freight.js";
import content_set_read_homework_after_8pm from "./set-read-homework-after-8pm.js";
import content_set_read_kitchen_window from "./set-read-kitchen-window.js";
import content_set_read_library_loans_graph from "./set-read-library-loans-graph.js";
import content_set_read_mixed_night_shift_poem from "./set-read-mixed-night-shift-poem.js";
import content_set_read_mixed_promise_quotations from "./set-read-mixed-promise-quotations.js";
import content_set_read_mixed_the_spare_key from "./set-read-mixed-the-spare-key.js";
import content_set_read_reef_notes_counts from "./set-read-reef-notes-counts.js";
import content_set_read_ridge_sketches from "./set-read-ridge-sketches.js";
import content_set_read_saturday_markets from "./set-read-saturday-markets.js";
import content_set_read_the_lantern_room from "./set-read-the-lantern-room.js";
import content_set_read_two_notes_on_a_bus_lane from "./set-read-two-notes-on-a-bus-lane.js";
import content_set_read_waiting_quotations from "./set-read-waiting-quotations.js";
import content_set_read_wind_farm_map_text from "./set-read-wind-farm-map-text.js";

export const READ_SETS = [content_set_read_bonus_fog_quotations, content_set_read_bonus_noticeboard, content_set_read_bonus_repair_caf_debate, content_set_read_bonus_two_weather_records, content_set_read_borrowing_voices, content_set_read_coastal_freight, content_set_read_homework_after_8pm, content_set_read_kitchen_window, content_set_read_library_loans_graph, content_set_read_mixed_night_shift_poem, content_set_read_mixed_promise_quotations, content_set_read_mixed_the_spare_key, content_set_read_reef_notes_counts, content_set_read_ridge_sketches, content_set_read_saturday_markets, content_set_read_the_lantern_room, content_set_read_two_notes_on_a_bus_lane, content_set_read_waiting_quotations, content_set_read_wind_farm_map_text].flat();
