// Auto-generated by the Upload button (see lib/content-manifest.js).
// Add content via Upload in the app — do not hand-edit this file, it
// gets overwritten on the next upload to this subject.

import content_set_abstract_complete_the_grid from "./set-abstract-complete-the-grid.js";
import content_set_abstract_extra_counters from "./set-abstract-extra-counters.js";
import content_set_abstract_extra_grid from "./set-abstract-extra-grid.js";
import content_set_abstract_extra_middle from "./set-abstract-extra-middle.js";
import content_set_abstract_extra_mixed from "./set-abstract-extra-mixed.js";
import content_set_abstract_extra_next from "./set-abstract-extra-next.js";
import content_set_abstract_middle_of_five from "./set-abstract-middle-of-five.js";
import content_set_abstract_next_in_sequence from "./set-abstract-next-in-sequence.js";
import content_set_abstract_week_pack_1_grid from "./set-abstract-week-pack-1-grid.js";
import content_set_abstract_week_pack_1_middle from "./set-abstract-week-pack-1-middle.js";
import content_set_abstract_week_pack_1_next from "./set-abstract-week-pack-1-next.js";
import content_set_abstract_week_pack_2_grid from "./set-abstract-week-pack-2-grid.js";
import content_set_abstract_week_pack_2_middle from "./set-abstract-week-pack-2-middle.js";
import content_set_abstract_week_pack_2_next from "./set-abstract-week-pack-2-next.js";
import content_set_abstract_week_pack_3_grid from "./set-abstract-week-pack-3-grid.js";
import content_set_abstract_week_pack_3_middle from "./set-abstract-week-pack-3-middle.js";
import content_set_abstract_week_pack_3_next from "./set-abstract-week-pack-3-next.js";
import content_set_abstract_week_pack_4_grid from "./set-abstract-week-pack-4-grid.js";
import content_set_abstract_week_pack_4_middle from "./set-abstract-week-pack-4-middle.js";
import content_set_abstract_week_pack_4_next from "./set-abstract-week-pack-4-next.js";
import content_set_abstract_week_pack_5_next from "./set-abstract-week-pack-5-next.js";
import content_set_abstract_week_pack_6_next from "./set-abstract-week-pack-6-next.js";
import content_set_abstract_week_pack_7_next from "./set-abstract-week-pack-7-next.js";
import content_set_abstract_week_pack_8_next from "./set-abstract-week-pack-8-next.js";

export const ABSTRACT_SETS = [content_set_abstract_complete_the_grid, content_set_abstract_extra_counters, content_set_abstract_extra_grid, content_set_abstract_extra_middle, content_set_abstract_extra_mixed, content_set_abstract_extra_next, content_set_abstract_middle_of_five, content_set_abstract_next_in_sequence, content_set_abstract_week_pack_1_grid, content_set_abstract_week_pack_1_middle, content_set_abstract_week_pack_1_next, content_set_abstract_week_pack_2_grid, content_set_abstract_week_pack_2_middle, content_set_abstract_week_pack_2_next, content_set_abstract_week_pack_3_grid, content_set_abstract_week_pack_3_middle, content_set_abstract_week_pack_3_next, content_set_abstract_week_pack_4_grid, content_set_abstract_week_pack_4_middle, content_set_abstract_week_pack_4_next, content_set_abstract_week_pack_5_next, content_set_abstract_week_pack_6_next, content_set_abstract_week_pack_7_next, content_set_abstract_week_pack_8_next].flat();
