// Auto-generated by the Upload button (see lib/content-manifest.js).
// Add content via Upload in the app — do not hand-edit this file, it
// gets overwritten on the next upload to this subject.

import content_set_write_advice_write_a_one_page_guide_to_the from "./set-write-advice-write-a-one-page-guide-to-the.js";
import content_set_write_advice_write_advice_for_someone_who_arrives from "./set-write-advice-write-advice-for-someone-who-arrives.js";
import content_set_write_creative_she_put_the_trophy_back_in from "./set-write-creative-she-put-the-trophy-back-in.js";
import content_set_write_discursive_a_rule_that_is_fair_on from "./set-write-discursive-a-rule-that-is-fair-on.js";
import content_set_write_discursive_being_first_is_not_the_same_2 from "./set-write-discursive-being-first-is-not-the-same-2.js";
import content_set_write_discursive_being_first_is_not_the_same from "./set-write-discursive-being-first-is-not-the-same.js";
import content_set_write_discursive_help_that_arrives_late_is_still from "./set-write-discursive-help-that-arrives-late-is-still.js";
import content_set_write_discursive_help_that_arrives_too_late_is from "./set-write-discursive-help-that-arrives-too-late-is.js";
import content_set_write_discursive_silence_is_not_always_agreement_2 from "./set-write-discursive-silence-is-not-always-agreement-2.js";
import content_set_write_discursive_silence_is_not_always_agreement from "./set-write-discursive-silence-is-not-always-agreement.js";
import content_set_write_discursive_we_keep_what_is_easy_to_2 from "./set-write-discursive-we-keep-what-is-easy-to-2.js";
import content_set_write_discursive_we_keep_what_is_easy_to from "./set-write-discursive-we-keep-what-is-easy-to.js";
import content_set_write_open_nobody_thanked_her_for_the_straightened from "./set-write-open-nobody-thanked-her-for-the-straightened.js";
import content_set_write_open_scene_the_last_light_in_the_street from "./set-write-open-scene-the-last-light-in-the-street.js";
import content_set_write_open_the_chain_on_the_dock_looked from "./set-write-open-the-chain-on-the-dock-looked.js";
import content_set_write_open_the_chair_at_the_end_was from "./set-write-open-the-chair-at-the-end-was.js";
import content_set_write_open_the_instructions_were_on_both_sides from "./set-write-open-the-instructions-were-on-both-sides.js";
import content_set_write_open_the_instructions_were_printed_on_both from "./set-write-open-the-instructions-were-printed-on-both.js";
import content_set_write_open_the_map_was_accurate_the_journey from "./set-write-open-the-map-was-accurate-the-journey.js";
import content_set_write_personal_reflective_the_map_was_accurate_the_journey from "./set-write-personal-reflective-the-map-was-accurate-the-journey.js";
import content_set_write_persuasive_should_year_6_run_the_canteen from "./set-write-persuasive-should-year-6-run-the-canteen.js";
import content_set_write_persuasive_the_talent_show_should_end_by from "./set-write-persuasive-the-talent-show-should-end-by.js";
import content_set_write_reflective_optional_she_had_learned_was_a from "./set-write-reflective-optional-she-had-learned-was-a.js";
import content_set_write_reflective_the_prize_was_not_what_she from "./set-write-reflective-the-prize-was-not-what-she.js";
import content_set_write_scene_she_left_the_trophy_box_open from "./set-write-scene-she-left-the-trophy-box-open.js";
import content_set_write_scene_the_last_computer_chair_was_already from "./set-write-scene-the-last-computer-chair-was-already.js";
import content_set_write_scene_the_oval_lights_came_on_too from "./set-write-scene-the-oval-lights-came-on-too.js";
import content_set_write_scene_the_spare_speech_was_still_in from "./set-write-scene-the-spare-speech-was-still-in.js";

export const WRITE_PROMPTS = [content_set_write_advice_write_a_one_page_guide_to_the, content_set_write_advice_write_advice_for_someone_who_arrives, content_set_write_creative_she_put_the_trophy_back_in, content_set_write_discursive_a_rule_that_is_fair_on, content_set_write_discursive_being_first_is_not_the_same_2, content_set_write_discursive_being_first_is_not_the_same, content_set_write_discursive_help_that_arrives_late_is_still, content_set_write_discursive_help_that_arrives_too_late_is, content_set_write_discursive_silence_is_not_always_agreement_2, content_set_write_discursive_silence_is_not_always_agreement, content_set_write_discursive_we_keep_what_is_easy_to_2, content_set_write_discursive_we_keep_what_is_easy_to, content_set_write_open_nobody_thanked_her_for_the_straightened, content_set_write_open_scene_the_last_light_in_the_street, content_set_write_open_the_chain_on_the_dock_looked, content_set_write_open_the_chair_at_the_end_was, content_set_write_open_the_instructions_were_on_both_sides, content_set_write_open_the_instructions_were_printed_on_both, content_set_write_open_the_map_was_accurate_the_journey, content_set_write_personal_reflective_the_map_was_accurate_the_journey, content_set_write_persuasive_should_year_6_run_the_canteen, content_set_write_persuasive_the_talent_show_should_end_by, content_set_write_reflective_optional_she_had_learned_was_a, content_set_write_reflective_the_prize_was_not_what_she, content_set_write_scene_she_left_the_trophy_box_open, content_set_write_scene_the_last_computer_chair_was_already, content_set_write_scene_the_oval_lights_came_on_too, content_set_write_scene_the_spare_speech_was_still_in].flat();
